import{useEffect,useMemo,useRef,useState}from'react';
import type{Confidence,Game,Phase,TagKind,TacticalFinding}from'./types';import{makeAdvice,suggestion}from'./engine';import{listGames,saveGame}from'./db';
const phases:Phase[]=['全体','オフェンス','ディフェンス','ブレイク','プレスダウン','リバウンド','トランジション'];
const fmt=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const demo:TacticalFinding[]=[
 {id:'d1',timestamp:48,quarter:'1Q',team:'dark',phase:'オフェンス',kind:'GOOD',finding:'右サイドのペイントタッチからコーナーを活用',evidence:'ヘルプを引きつけてエクストラパスまでつながった',confidence:'高',priority:2,recommendation:'同じ形を継続',createdAt:new Date().toISOString()},
 {id:'d2',timestamp:102,quarter:'1Q',team:'dark',phase:'ディフェンス',kind:'FIX',finding:'相手7番の右ドライブから崩されている',evidence:'3線ヘルプ後の逆サイドローテーションが遅れた',confidence:'中',priority:1,recommendation:'右を切って左へ誘導し、3線は一歩早く準備',createdAt:new Date().toISOString()},
 {id:'d3',timestamp:155,quarter:'1Q',team:'dark',phase:'オフェンス',kind:'GOOD',finding:'オフェンスリバウンドからセカンドショット',evidence:'先に身体を当てて再攻撃を得点につなげた',confidence:'高',priority:2,recommendation:'ヒットしてからボールへ向かう',createdAt:new Date().toISOString()}];

export default function App(){
 const video=useRef<HTMLVideoElement>(null);const[fileUrl,setFileUrl]=useState('');const[time,setTime]=useState(0);const[duration,setDuration]=useState(240);const[playing,setPlaying]=useState(false);const[phase,setPhase]=useState<Phase>('全体');const[team,setTeam]=useState<'dark'|'light'>('dark');const[findings,setFindings]=useState<TacticalFinding[]>([]);const[confidence,setConfidence]=useState<Confidence>('中');const[note,setNote]=useState('');const[quarter,setQuarter]=useState('1Q');const[advice,setAdvice]=useState(()=>makeAdvice([]));const[demoMode,setDemoMode]=useState(false);const[saved,setSaved]=useState<Game[]>([]);const[toast,setToast]=useState('');
 const [meta,setMeta]=useState({name:'新しい試合',opponent:'',date:new Date().toISOString().slice(0,10)});
 useEffect(()=>{listGames().then(setSaved).catch(()=>{})},[]);useEffect(()=>()=>{if(fileUrl)URL.revokeObjectURL(fileUrl)},[fileUrl]);
 const current=suggestion(phase,'CHECK');const ordered=useMemo(()=>[...findings].sort((a,b)=>b.timestamp-a.timestamp),[findings]);
 function flash(x:string){setToast(x);setTimeout(()=>setToast(''),1800)}
 function add(kind:TagKind){const base=suggestion(phase,kind);const item:TacticalFinding={id:crypto.randomUUID(),timestamp:time,quarter,team,phase,kind,finding:note.trim()||base.finding,evidence:base.evidence,confidence,priority:kind==='FIX'?1:kind==='CHECK'?2:3,recommendation:base.recommendation,createdAt:new Date().toISOString()};setFindings(x=>[...x,item]);setNote('');flash(kind==='GOOD'?'GOOD PLAYを保存しました':'タイムラインに記録しました')}
 function loadDemo(){setDemoMode(true);setFindings(demo);setDuration(240);setTime(102);setMeta({name:'DEMO｜秋季リーグ 第1戦',opponent:'West Hawks',date:new Date().toISOString().slice(0,10)});setAdvice(makeAdvice(demo));flash('デモデータを読み込みました')}
 function seek(t:number){setTime(t);if(video.current){video.current.currentTime=t;video.current.play().catch(()=>{})}document.querySelector('.video-card')?.scrollIntoView({behavior:'smooth'})}
 async function persist(){const game:Game={id:meta.name+meta.date,name:meta.name,date:meta.date,opponent:meta.opponent,team,videoName:video.current?.dataset.name,findings,advice,updatedAt:new Date().toISOString()};await saveGame(game);setSaved(await listGames());flash('端末内に保存しました')}
 function generate(){const a=makeAdvice(findings);setAdvice(a);flash('直近のプレーから整理しました')}
 function exportJson(){download(JSON.stringify({meta,team,findings,advice},null,2),'game-analysis.json','application/json')}
 function exportCsv(){const rows=[['時刻','Q','評価','視点','内容','根拠','信頼度','提案'],...ordered.map(x=>[fmt(x.timestamp),x.quarter,x.kind,x.phase,x.finding,x.evidence,x.confidence,x.recommendation])];download(rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'timeline.csv','text/csv;charset=utf-8')}
 function download(data:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
 const reviews=useMemo(()=>({good:findings.filter(x=>x.kind==='GOOD').slice(-3),fix:findings.filter(x=>x.kind!=='GOOD').sort((a,b)=>a.priority-b.priority).slice(0,3)}),[findings]);
 return <div className="app">
  <header><div className="brand"><div className="ball">●</div><div><b>TACTICAL ANALYZER</b><span>COURTSIDE / LOCAL-FIRST</span></div></div><div className="privacy">● 映像は端末内のみ <span>OFFLINE READY</span></div></header>
  <section className="matchbar"><label>GAME<input value={meta.name} onChange={e=>setMeta({...meta,name:e.target.value})}/></label><label>OPPONENT<input value={meta.opponent} placeholder="対戦相手" onChange={e=>setMeta({...meta,opponent:e.target.value})}/></label><label>DATE<input type="date" value={meta.date} onChange={e=>setMeta({...meta,date:e.target.value})}/></label><button className="save" onClick={persist}>▣ 試合を保存</button></section>
  <nav className="phases" aria-label="解析視点">{phases.map(p=><button className={p===phase?'active':''} onClick={()=>setPhase(p)} key={p}>{p==='オフェンス'?'OFFENSE':p==='ディフェンス'?'DEFENSE':p==='ブレイク'?'BREAK':p==='プレスダウン'?'PRESS':p}</button>)}</nav>
  <main><section className="video-card">
   <div className="section-title"><span>01</span> GAME FILM <em>{demoMode?'DEMO MODE':'LOCAL VIDEO'}</em></div>
   <div className="video-wrap">{fileUrl?<video ref={video} src={fileUrl} controls playsInline onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onDurationChange={e=>setDuration(e.currentTarget.duration||240)}/>:<div className="empty"><div className="play">▶</div><h2>試合動画を読み込む</h2><p>MP4 / MOV / WebM · 外部へアップロードしません</p><label className="file">＋ 動画を選択<input hidden type="file" accept="video/mp4,video/quicktime,video/webm,video/*" onChange={e=>{const f=e.target.files?.[0];if(f){setFileUrl(URL.createObjectURL(f));setDemoMode(false)}}}/></label><button className="demo" onClick={loadDemo}>動画なしで DEMO MODE</button></div>}</div>
   {!fileUrl&&demoMode&&<div className="fake-controls"><button onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'}</button><b>{fmt(time)}</b><input aria-label="動画位置" type="range" min="0" max={duration} value={time} onChange={e=>setTime(+e.target.value)}/><span>{fmt(duration)}</span></div>}
   <div className="team-select"><span>解析するチーム</span><button className={team==='dark'?'chosen dark':''} onClick={()=>setTeam('dark')}><i/>濃色チーム <small>濃</small></button><button className={team==='light'?'chosen light':''} onClick={()=>setTeam('light')}><i/>淡色チーム <small>淡</small></button></div>
   <details><summary>⌖ 解析補助モード・詳細入力</summary><p>Phase 1では手動タグを優先。将来の選手・ボール追跡は映像解析層として独立追加できます。</p></details>
  </section>
  <aside><div className="section-title"><span>02</span> LIVE OBSERVATION <em>{phase}</em></div><div className="clock"><select value={quarter} onChange={e=>setQuarter(e.target.value)}>{['1Q','2Q','3Q','4Q','OT'].map(q=><option>{q}</option>)}</select><strong>{fmt(time)}</strong><small>VIDEO TIME</small></div>
   <label className="note">観察メモ（任意）<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={current.finding}/></label><div className="confidence"><span>信頼度</span>{(['高','中','低','判断困難'] as Confidence[]).map(c=><button className={confidence===c?'on':''} onClick={()=>setConfidence(c)}>{c}</button>)}</div>
   <div className="tag-buttons"><button className="good" onClick={()=>add('GOOD')}>★<b>GOOD PLAY</b><small>続けたいプレー</small></button><button className="check" onClick={()=>add('CHECK')}>?<b>CHECK</b><small>確認したい点</small></button><button className="fix" onClick={()=>add('FIX')}>!<b>FIX</b><small>直すべき点</small></button></div>
   <button className="coach-cta" onClick={generate}><span>今すぐ選手に伝える</span><small>直近のプレーから1〜2分の要点を生成 →</small></button>
   <div className="coach-card"><div className="card-head"><b>COACHING CARD</b><span>最大3ポイント</span></div><Advice n="01" title="現在の状況" text={advice.situation}/><Advice n="02" title="良かった点・継続" text={advice.positive} good/><Advice n="03" title="直すべき点" text={advice.fix}/><div className="next"><b>次の3ポゼッションでやること</b><p>{advice.nextThree}</p></div><small className="caution">AIは整理を補助します。映像が不鮮明な判断はコーチが修正してください。</small></div>
  </aside></main>
  <section className="timeline"><div className="section-title"><span>03</span> GAME TIMELINE <em>{findings.length} EVENTS</em></div>{ordered.length?<div className="timeline-list">{ordered.map(x=><button key={x.id} onClick={()=>seek(x.timestamp)}><time>{x.quarter}<b>{fmt(x.timestamp)}</b></time><span className={'pill '+x.kind.toLowerCase()}>{x.kind}</span><span><b>{x.finding}</b><small>{x.phase} · {x.evidence}</small></span><em>信頼度 {x.confidence}</em><i>▶</i></button>)}</div>:<div className="no-events">動画位置で GOOD / CHECK / FIX を押すと、ここに記録されます。</div>}</section>
  <section className="review"><div className="section-title"><span>04</span> POST-GAME REVIEW <em>試合後レビュー</em></div><div className="review-grid"><article><h3>今日うまくいった攻撃 / 繰り返したいこと</h3>{reviews.good.length?reviews.good.map(x=><p>✓ {x.finding}<small>{x.recommendation}</small></p>):<p className="muted">GOOD PLAYを記録してください</p>}</article><article><h3>最も修正すべきこと / 次回の練習</h3>{reviews.fix.length?reviews.fix.map(x=><p>→ {x.finding}<small>{x.recommendation}</small></p>):<p className="muted">CHECK / FIXを記録してください</p>}</article></div><div className="exports"><button onClick={()=>window.print()}>▤ HTML / PDF印刷</button><button onClick={exportJson}>{ } JSONバックアップ</button><button onClick={exportCsv}>▦ CSV</button></div></section>
  {saved.length>0&&<section className="saved"><h3>端末に保存した試合</h3>{saved.map(g=><button onClick={()=>{setMeta({name:g.name,date:g.date,opponent:g.opponent});setTeam(g.team);setFindings(g.findings);setAdvice(g.advice??makeAdvice(g.findings));flash('保存試合を開きました')}}>{g.name}<small>{g.date} · {g.findings.length} events</small></button>)}</section>}
  <footer>映像はアップロードされません · 外部AI機能はオフラインでは利用できません · Phase 1</footer>{toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
function Advice({n,title,text,good=false}:{n:string,title:string,text:string,good?:boolean}){return <div className={'advice '+(good?'positive':'')}><span>{n}</span><div><b>{title}</b><p>{text}</p></div></div>}
